site_name: IAHLT Arabic NER
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - toc.integrate
    - toc.github
    - toc.sections
    - search.highlight
    - search.suggest
    - code-highlighting
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
    - navigation.tabs
    - navigation.sections
    - navigation.path
markdown_extensions:
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.mark
  - attr_list
  - pymdownx.tabbed:
      alternate_style: true

copyright: Copyright &copy; 2024 <a href="https://www.iahlt.org/" target="_blank" rel="noopener">IAHLT</a>

extra_javascript:
  - javascripts/katex.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.9/katex.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.9/contrib/auto-render.min.js

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.9/katex.min.css

nav:
  - Dataset: index.md
  - Training: training.md
  - Evaluation: evaluation.md
  - Models: usage.md
  - Annotation Guideline: annotation.md
  - Data and Models access: access.md


extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/IAHLT
  generator: false

